# Base image for installing dependencies
FROM node:20-alpine AS base

RUN npm install -g pnpm
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --no-cache --no-optional && pnpm store prune

# Final development image
FROM base AS dev

WORKDIR /app
COPY --from=base /app/node_modules /app/node_modules
COPY . .

EXPOSE 5000

CMD ["pnpm", "dev"]
